name: GeoTIFF-Reader App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        make install
    - name: Format with black
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Deploy an App Engine app
      uses: google-github-actions/deploy-appengine@v0.1.0
      with:
        project: ${{ secrets.gcp_project }}
        deliverables: app.yaml
        credentials: ${{ secrets.gcp_credentials }}